### ISSUE TITLE
discuss next problem

### ISSUE THREAD

**Issue by Dave0107** [Dave0107/EcommerceSystem-MERN#2]
Which type of language do we use in backend side?

**Comment by Dave0107** [comment]
What do you think about this?

**Comment by dev188007** [comment]
I think we should use Django,,

**Comment by Dave0107** [comment]
Yes I agree with you.

**Comment by Dave0107** [comment]
> What do you think about this?



> Yes I agree with you.

Of Course. I believe you.
Let's begin.

**Comment by dev188007** [comment]
ok?
